version: '3'
services:
  build:
    image: gradle
    volumes:
      - "./webapp:/project"
    working_dir: /project
    command: ["gradle", "-t", "build", "cargoRedeployRemote"]
    depends_on:
      - appserver
  appserver:
    build: wildfly/.
    image: sightseeker/wildfly-deployment-demo
    ports:
      - 8080:8080
      - 9990:9990
